[book]
title = "От объекта к системе"
#subtitle = "Как модель реального мира определяет архитектуру цифровых платформ"
authors = ["Mikhail.A.I."]
language = "ru"
description = "Книга о моделировании инженерных объектов и архитектуре цифровых платформ"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/Taryon-ru/from-object-to-system"
edit-url-template = "https://github.com/Taryon-ru/from-object-to-system/edit/main/src/{path}"
additional-css = ["src/custom.css"]
#additional-js = ["navigation.js"]

[build]
build-dir = "book"
